center
hide all
color grey80
set cartoon_flat_sheets, 0
set cartoon_smooth_loops, 0
show cartoon
select resi 57
show spheres, sele
color red, sele
select resi 56
show spheres, sele
color red, sele
select resi 31
show spheres, sele
color red, sele
select resi 83
show spheres, sele
color orange, sele
select resi 43
show spheres, sele
color orange, sele
select resi 37
show spheres, sele
color orange, sele
select resi 65
show spheres, sele
color orange, sele
select resi 58
show spheres, sele
color orange, sele
select resi 68
show spheres, sele
color orange, sele
select resi 72
show spheres, sele
color orange, sele
select resi 55
show spheres, sele
color orange, sele
select resi 47
show spheres, sele
color orange, sele
select resi 54
color yelloworange, sele
select resi 81
color yelloworange, sele
select resi 33
color yelloworange, sele
select resi 34
color yelloworange, sele
select resi 32
color yelloworange, sele
select resi 82
color yelloworange, sele
select resi 85
color yelloworange, sele
select resi 44
color yelloworange, sele
select resi 84
color yelloworange, sele
select resi 96
color yelloworange, sele
select resi 125
color yelloworange, sele
select resi 98
color yelloworange, sele
select resi 59
color yelloworange, sele
select resi 120
color yelloworange, sele
select resi 52
color yelloworange, sele
select resi 39
color yelloworange, sele
select resi 115
color yelloworange, sele
select resi 35
color yelloworange, sele
select resi 118
color yelloworange, sele
select resi 114
color yelloworange, sele
select resi 80
color yelloworange, sele
select resi 119
color yelloworange, sele
select resi 99
color yelloworange, sele
select resi 30
color yelloworange, sele
select resi 36
color yelloworange, sele
select resi 95
color yelloworange, sele
select resi 42
color yelloworange, sele
select resi 91
color yelloworange, sele
select resi 46
color yelloworange, sele
select resi 29
color yelloworange, sele
select resi 97
color yelloworange, sele
select resi 60
color yelloworange, sele
select resi 64
color yelloworange, sele
select resi 88
color yelloworange, sele
select resi 53
color yelloworange, sele
select resi 62
color yelloworange, sele
select resi 71
color yelloworange, sele
select resi 86
color yelloworange, sele
select resi 101
color yelloworange, sele
select resi 77
color yelloworange, sele
select resi 92
color yelloworange, sele
select resi 100
color yelloworange, sele
select resi 40
color yelloworange, sele
select resi 75
color yelloworange, sele
select resi 49
color yelloworange, sele
select resi 117
color yelloworange, sele
select resi 102
color yelloworange, sele
select resi 87
color yelloworange, sele
select resi 48
color yelloworange, sele
select resi 69
color yelloworange, sele
select resi 116
color yelloworange, sele
select resi 93
color yelloworange, sele
select resi 17
color yelloworange, sele
select resi 51
color yelloworange, sele
select resi 45
color yelloworange, sele
select resi 104
color yelloworange, sele
select resi 105
color yelloworange, sele
select resi 79
color yelloworange, sele
select resi 18
color yelloworange, sele
select resi 89
color yelloworange, sele
select resi 41
color yelloworange, sele
select resi 129
color yelloworange, sele
select resi 106
color yelloworange, sele
select resi 50
color yelloworange, sele
select resi 26
color yelloworange, sele
select resi 128
color yelloworange, sele
select none

